APP_TITLE = "Menu Extraction Agent"
MODEL_NAME = "gemini-2.5-flash"
MAX_IMAGE_SIZE_MB = 20
MAX_IMAGE_DIMENSION = 1568
BLUR_THRESHOLD_WARNING = 50.0
BLUR_THRESHOLD_ERROR = 10.0
SUPPORTED_FORMATS = ["jpg", "jpeg", "png", "webp"]
MAX_TOKENS = 8192
